#![cfg_attr(rustfmt, rustfmt::skip)]
//! Generated ASN.1 code
//!
//! This module contains all the generated ASN.1 structures and re-exports them
//! for use throughout the library.
//!
//! This file is automatically generated by build.rs - do not edit manually.

#[path = "generated/sensitive_attributes.rs"]
mod sensitive_attributes;
#[path = "generated/kyc_attributes.rs"]
mod kyc_attributes;

#[path = "generated/from_impls.rs"]
mod from_impls;
#[path = "generated/builder_ext.rs"]
pub mod builder_ext;

// Re-export all types from the generated modules
pub use sensitive_attributes::{SensitiveAttributeCipher, SensitiveAttributeHashedValue, SensitiveAttribute};
pub use kyc_attributes::{AttributeValue, Attribute, KycAttributes};
#[path = "generated/attribute_types.rs"]
pub mod attribute_types;
