use rasn_compiler::RasnCompiler;
use std::path::Path;

fn main() {
	let out_dir = "src/generated";
	let asn_dir = "asn1";

	// Create output dir if missing
	if !Path::new(out_dir).exists() {
		std::fs::create_dir_all(out_dir).expect("Failed to create generated output directory");
	}

	// Find all .asn files in the asn1 directory
	let asn_files = std::fs::read_dir(asn_dir)
		.expect("Failed to read asn1 directory")
		.filter_map(|entry| {
			let entry = entry.ok()?;
			let path = entry.path();
			if path.extension()? == "asn" {
				Some(path)
			} else {
				None
			}
		})
		.collect::<Vec<_>>();

	// Compile each ASN.1 file
	for asn_file in &asn_files {
		let output_file = Path::new(out_dir).join(asn_file.file_stem().unwrap().to_string_lossy().to_string() + ".rs");

		let result = RasnCompiler::new()
			.add_asn_by_path(asn_file)
			.compile_to_string();

		match result {
			Ok(compile_result) => {
				let generated_code = compile_result.generated;

				// Remove module wrapper by extracting the inner content
				let processed_code = remove_module_wrapper(&generated_code);

				// Add lint suppressions for generated code
				let final_code = add_lint_suppressions(&processed_code);

				// Write the processed code to file
				std::fs::write(&output_file, final_code).expect("Failed to write generated file");

				for warning in compile_result.warnings {
					println!("cargo:warning=ASN.1 compilation warning: {warning:?}");
				}
			}
			Err(error) => {
				panic!("ASN.1 compilation failed for {asn_file:?}: {error:?}");
			}
		}

		println!("cargo:rerun-if-changed={}", asn_file.display());
	}

	println!("cargo:rerun-if-changed={asn_dir}");
}

fn remove_module_wrapper(code: &str) -> String {
	// Look for pattern: pub mod module_name {
	let lines: Vec<&str> = code.lines().collect();

	// Find the start and end of the module
	let mut start_idx = None;
	let mut end_idx = None;
	let mut brace_count = 0;

	for (i, line) in lines.iter().enumerate() {
		let trimmed = line.trim();

		// Look for pub mod declaration
		if trimmed.starts_with("pub mod ") && trimmed.ends_with(" {") {
			start_idx = Some(i);
			brace_count = 1;
			continue;
		}

		// If we're inside a module, track braces
		if start_idx.is_some() && end_idx.is_none() {
			brace_count += line.matches('{').count();
			brace_count -= line.matches('}').count();

			if brace_count == 0 {
				end_idx = Some(i);
				break;
			}
		}
	}

	// If we found a module wrapper, extract the content
	let inner_content = if let (Some(start), Some(end)) = (start_idx, end_idx) {
		// Extract lines between the module declaration and closing brace
		let inner_lines = &lines[start + 1..end];

		// Remove one level of indentation (typically one tab)
		let processed_lines: Vec<String> = inner_lines
			.iter()
			.map(|line| {
				if let Some(stripped) = line.strip_prefix('\t') {
					stripped
				} else if let Some(stripped) = line.strip_prefix("    ") {
					stripped
				} else {
					line
				}
			})
			.map(|s| s.to_string())
			.collect();

		processed_lines.join("\n")
	} else {
		// No module wrapper found, return as-is
		code.to_string()
	};

	// Clean up unused imports
	clean_unused_imports(&inner_content)
}

fn clean_unused_imports(code: &str) -> String {
	// Split into lines and filter out common unused imports
	let lines: Vec<&str> = code.lines().collect();
	let mut cleaned_lines = Vec::new();

	for line in lines {
		let trimmed = line.trim();

		// Skip unused imports commonly generated by rasn-compiler
		if trimmed == "use core::borrow::Borrow;"
			|| trimmed == "use std::sync::LazyLock;"
			|| (trimmed == "extern crate alloc;" && code.contains("use rasn::prelude::*;"))
		{
			continue;
		}

		cleaned_lines.push(line);
	}

	cleaned_lines.join("\n")
}

fn add_lint_suppressions(code: &str) -> String {
	// Add comprehensive lint suppressions at the top of the file
	let suppressions = [
		"#![allow(unused_imports)]",
		"#![allow(unused_variables)]",
		"#![allow(dead_code)]",
		"#![allow(non_camel_case_types)]",
		"#![allow(non_snake_case)]",
		"#![allow(non_upper_case_globals)]",
		"#![allow(clippy::all)]",
		"", // Empty line for readability
	];

	let mut result = suppressions.join("\n");
	result.push_str(code);
	result
}
