// Emit binding DTOs from the TypeScript `@keetanetwork/anchor` package's
// `accountJSONSchema`.

import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import fs from "node:fs";
import path from "node:path";

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

/** One DTO emission: a quicktype language and where its output lands. */
interface DtoTarget {
	/** The quicktype `--lang` value. */
	lang: string;
	/** Extra quicktype options for this language. */
	options: string[];
	/** The generated file, relative to the repo root. */
	output: string;
	/** Header lines prepended to the generated file. */
	header: string[];
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(packageDir, "..");

// The anchor package is installed for the interop harness; resolve its emitted
// address schema from there rather than adding a second install.
const harnessDir = path.join(repoRoot, "keetanetwork-anchor-client", "node-harness");
const harnessRequire = createRequire(path.join(harnessDir, "package.json"));
const schemaModule = "@keetanetwork/anchor/services/asset-movement/lib/data/addresses/types.generated.js";

const quickTypeBin = path.join(packageDir, "node_modules", ".bin", "quicktype");

const generatedNotice = [
	"Generated by scripts/src/gen-dtos.ts from @keetanetwork/anchor accountJSONSchema.",
	"Do not edit by hand; run `make dtos` to regenerate."
];

const targets: DtoTarget[] = [
	{
		lang: "csharp",
		options: [
			"--namespace", "KeetaNet.Anchor.Kyc.Generated",
			"--framework", "SystemTextJson",
			"--array-type", "list",
			"--number-type", "double"
		],
		output: path.join(
			"keetanetwork-anchor-client-wasi",
			"bindings",
			"csharp",
			"KeetaNet.Anchor.Kyc",
			"Generated",
			"AddressTypes.cs"
		),
		// The binding compiles with warnings-as-errors, so mark the file
		// generated and silence warnings for it.
		header: [
			"// <auto-generated />",
			...generatedNotice.map((line) => `// ${line}`),
			"#pragma warning disable"
		]
	}
];

/**
 * The JSON Schema `type` keyword matching a `const` literal's runtime type.
 *
 * @param literal - The literal the `const` carried.
 * @returns The schema type name.
 */
function literalType(literal: JsonValue | undefined): string {
	if (typeof literal === "boolean") {
		return("boolean");
	}
	if (typeof literal === "number") {
		return("number");
	}

	return("string");
}

/*
 * quicktype's schema reader rejects a bare `const` (it assumes a string and
 * calls `codePointAt`); rewrite each `const` as a single-value `enum` with an
 * explicit type, which preserves the discriminator while quicktype can read it.
 */
function normalizeConsts(node: JsonValue): JsonValue {
	if (Array.isArray(node)) {
		return(node.map(normalizeConsts));
	}
	if (node === null || typeof node !== "object") {
		return(node);
	}

	const rewritten: { [key: string]: JsonValue } = {};
	for (const [key, value] of Object.entries(node)) {
		rewritten[key] = normalizeConsts(value);
	}

	if (Object.hasOwn(rewritten, "const")) {
		const literal = rewritten["const"];
		delete rewritten["const"];
		rewritten["enum"] = [literal ?? null];
		rewritten["type"] = literalType(literal);
	}

	return(rewritten);
}

/**
 * Whether `value` is a plain JSON object (not null, not an array).
 *
 * @param value - The value to check.
 * @returns Whether `value` is a plain JSON object.
 */
function isJsonObject(value: unknown): value is { [key: string]: JsonValue } {
	return(value !== null && typeof value === "object" && !Array.isArray(value));
}

/**
 * Load the address schema from the anchor package.
 *
 * @returns The address schema.
 */
function loadAddressSchema(): JsonValue {
	const loaded: unknown = harnessRequire(schemaModule);
	const accountJSONSchema = isJsonObject(loaded) ? loaded['accountJSONSchema'] : undefined;
	if (!isJsonObject(accountJSONSchema)) {
		throw(new Error(`accountJSONSchema not found in ${schemaModule}`));
	}

	// Root the schema at the two top address unions so quicktype reaches every
	// member (and only address members) transitively.
	return(normalizeConsts({
		...accountJSONSchema,
		oneOf: [
			{ $ref: "#/definitions/GeneratedAddressResolved" },
			{ $ref: "#/definitions/GeneratedAddressObfuscated" }
		]
	}));
}

/**
 * Run quicktype to generate the DTOs for a target language.
 *
 * @param schemaFile - The path to the schema file.
 * @param target - The target language.
 * @param outputFile - The path to the output file.
 */
function runQuickType(schemaFile: string, target: DtoTarget, outputFile: string): void {
	const result = spawnSync(
		quickTypeBin,
		["--src-lang", "schema", "--lang", target.lang, ...target.options, "-o", outputFile, schemaFile],
		{ stdio: "inherit" }
	);

	if (result.status !== 0) {
		throw(new Error(`quicktype (${target.lang}) exited with status ${result.status ?? "unknown"}`));
	}
}

/**
 * Emit the DTOs for a target language.
 *
 * @param schemaFile - The path to the schema file.
 * @param target - The target language.
 */
function emitTarget(schemaFile: string, target: DtoTarget): void {
	const outputFile = path.join(repoRoot, target.output);
	fs.mkdirSync(path.dirname(outputFile), { recursive: true });
	runQuickType(schemaFile, target, outputFile);

	const generated = fs.readFileSync(outputFile, "utf8");
	fs.writeFileSync(outputFile, `${target.header.join("\n")}\n\n${generated}`);
	process.stdout.write(`Wrote ${target.output}\n`);
}

function main(): void {
	const schema = loadAddressSchema();
	const schemaFile = path.join(packageDir, ".account.schema.json");
	fs.writeFileSync(schemaFile, JSON.stringify(schema));

	try {
		for (const target of targets) {
			emitTarget(schemaFile, target);
		}
	} finally {
		fs.rmSync(schemaFile, { force: true });
	}
}

main();
