use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use keetanetwork_utils::build::{compile_asn1_directory_with_full_config, Asn1CompileConfig};
use serde_json::{Map, Value};

fn main() {
	// Generate ASN.1 code
	let config = Asn1CompileConfig::new("asn1", "src/generated")
		.with_generated_rs_path("src/generated.rs")
		.with_remove_module_wrappers(true)
		.with_public_modules(vec!["iso20022"]);

	if let Err(e) = compile_asn1_directory_with_full_config(&config) {
		panic!("ASN.1 compilation failed: {e}");
	}

	// Load OID data once for all generators
	let oids = load_oids_json();

	// Generate From implementations for wrapper types
	generate_attribute_from_impl(&oids);
	// Generate the builder trait extension
	generate_builder_trait_extension(&oids);
	// Generate the OID -> ASN.1 value type registry used by the schema-aware codec
	generate_attribute_value_types(&oids);
	// Generate the declarative iso20022 schema descriptors used by the engine
	generate_iso20022_schema(&oids);
}

/// Format an OID array as a dotted-decimal string (e.g. `1.3.6.1.4.1.62675.1.0`).
fn format_oid_dotted(oid_array: &[Value]) -> String {
	oid_array
		.iter()
		.filter_map(|v| v.as_u64())
		.map(|n| n.to_string())
		.collect::<Vec<String>>()
		.join(".")
}

/// Generate the OID -> ASN.1 value type registry.
fn generate_attribute_value_types(oids: &Value) {
	let dest_path = Path::new("src/generated").join("attribute_types.rs");

	// (oid_dotted, AttributeValueType variant expression)
	let mut entries: Vec<(String, String)> = Vec::new();

	let mut collect = |attrs: Option<&serde_json::Map<String, Value>>, default_type: &str| {
		if let Some(attrs) = attrs {
			for info in attrs.values() {
				if let Some(oid_array) = info["oid"].as_array() {
					let oid = format_oid_dotted(oid_array);
					let type_str = info["type"].as_str().unwrap_or(default_type);
					let token = info["token"].as_str().unwrap_or_default();
					let variant = match type_str {
						"UTF8String" => "AttributeValueType::Utf8String".to_string(),
						"GeneralizedTime" => "AttributeValueType::GeneralizedTime".to_string(),
						_ => format!("AttributeValueType::Structured(\"{token}\")"),
					};
					entries.push((oid, variant));
				}
			}
		}
	};

	collect(oids["plain_attributes"].as_object(), "UTF8String");
	collect(oids["sensitive_attributes"].as_object(), "UTF8String");

	entries.sort_by(|a, b| a.0.cmp(&b.0));
	entries.dedup_by(|a, b| a.0 == b.0);

	let mut arms = String::new();
	for (oid, variant) in &entries {
		arms.push_str(&format!("\t\t\"{oid}\" => Some({variant}),\n"));
	}

	let generated_code = format!(
		r#"//! Generated registry mapping KYC attribute OIDs to their ASN.1 value type.
//!
//! This file is automatically generated by build.rs - do not edit manually.

/// The ASN.1 value type of a KYC attribute.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttributeValueType {{
	/// A UTF-8 string value (DER `UTF8String`).
	Utf8String,
	/// A timestamp value (DER `GeneralizedTime`).
	GeneralizedTime,
	/// A structured `SEQUENCE`/`CHOICE` value; the token is the iso20022 type name.
	Structured(&'static str),
}}

/// Resolve the ASN.1 value type for a KYC attribute OID in dotted-decimal form.
pub fn attribute_value_type(oid: &str) -> Option<AttributeValueType> {{
	match oid {{
{arms}		_ => None,
	}}
}}
"#
	);

	if let Some(parent) = dest_path.parent() {
		fs::create_dir_all(parent).expect("Failed to create src/generated directory");
	}

	fs::write(&dest_path, generated_code).expect("Failed to write attribute_types.rs");

	ensure_generated_module("attribute_types", true);
}

/// Ensure `src/generated.rs` declares a generated submodule exactly once.
fn ensure_generated_module(module: &str, public: bool) {
	let generated_rs_path = Path::new("src/generated.rs");
	let current_content = fs::read_to_string(generated_rs_path).expect("Failed to read generated.rs");

	let mod_decl = if public {
		format!("pub mod {module};")
	} else {
		format!("mod {module};")
	};

	if current_content.contains(&mod_decl) {
		return;
	}

	let path_attr = format!("#[path = \"generated/{module}.rs\"]");
	let mut updated = current_content.trim_end().to_string();
	updated.push('\n');
	updated.push_str(&path_attr);
	updated.push('\n');
	updated.push_str(&mod_decl);
	updated.push('\n');

	fs::write(generated_rs_path, updated).expect("Failed to update generated.rs");
}

/// Generate the declarative iso20022 [`Schema`] descriptors consumed by the
/// engine (`iso20022_engine::attribute_schema`).
fn generate_iso20022_schema(oids: &Value) {
	let mut generator = SchemaGenerator::new(oids);

	let mut tokens = structured_tokens(oids);
	tokens.sort();

	let mut arms = String::new();
	for token in &tokens {
		let expr = generator.member_expr(token);
		arms.push_str(&format!("\t\t\"{token}\" => Some({expr}),\n"));
	}

	let mut builders = generator.builders;
	builders.sort_by(|a, b| a.0.cmp(&b.0));

	let mut body = String::new();
	for (name, definition) in &builders {
		body.push_str(&format!("fn {name}() -> Schema {{\n\t{definition}\n}}\n\n"));
	}

	let generated_code = format!(
		r#"//! Generated declarative iso20022 schema descriptors.
//!
//! This file is automatically generated by build.rs - do not edit manually. It
//! is derived from `oids.json`.

use alloc::boxed::Box;
use alloc::vec;

use keetanetwork_asn1::schema_codec::{{Field, Schema}};

/// Resolve the declarative schema for a structured KYC attribute token.
pub fn attribute_schema(token: &str) -> Option<Schema> {{
	match token {{
{arms}		_ => None,
	}}
}}

{body}"#
	);

	let dest_path = Path::new("src/generated").join("iso20022_schema.rs");
	if let Some(parent) = dest_path.parent() {
		fs::create_dir_all(parent).expect("Failed to create src/generated directory");
	}
	fs::write(&dest_path, generated_code).expect("Failed to write iso20022_schema.rs");

	ensure_generated_module_serde("iso20022_schema");
}

/// The sensitive-attribute tokens whose value is structured (not a scalar
/// `UTF8String`/`GeneralizedTime`), each of which needs a generated schema.
fn structured_tokens(oids: &Value) -> Vec<String> {
	let mut tokens = Vec::new();
	if let Some(attrs) = oids["sensitive_attributes"].as_object() {
		for info in attrs.values() {
			let (Some(token), Some(type_str)) = (info["token"].as_str(), info["type"].as_str()) else {
				continue;
			};
			if !matches!(type_str, "UTF8String" | "GeneralizedTime") {
				tokens.push(token.to_string());
			}
		}
	}

	tokens
}

/// Resolves named iso20022 types from `oids.json` into Rust `Schema` expressions,
/// emitting a builder function per named `SEQUENCE`/`CHOICE` type.
struct SchemaGenerator {
	primitives: Map<String, Value>,
	choices: Map<String, Value>,
	enumerations: Map<String, Value>,
	sequences: Map<String, Value>,
	ext_structs: Map<String, Value>,
	sensitive_by_token: Map<String, Value>,
	visited: BTreeSet<String>,
	builders: Vec<(String, String)>,
}

impl SchemaGenerator {
	fn new(oids: &Value) -> Self {
		let object = |value: &Value| value.as_object().cloned().unwrap_or_default();
		let iso = &oids["iso20022_types"];

		let mut ext_structs = Map::new();
		if let Some(extensions) = oids["extensions"].as_object() {
			for (name, def) in extensions {
				if def.get("fields").is_some() {
					ext_structs.insert(name.clone(), def.clone());
				}
			}
		}

		let mut sensitive_by_token = Map::new();
		if let Some(attrs) = oids["sensitive_attributes"].as_object() {
			for def in attrs.values() {
				if let Some(token) = def["token"].as_str() {
					sensitive_by_token.insert(token.to_string(), def.clone());
				}
			}
		}

		Self {
			primitives: object(&iso["primitives"]),
			choices: object(&iso["choices"]),
			enumerations: object(&iso["enumerations"]),
			sequences: object(&iso["sequences"]),
			ext_structs,
			sensitive_by_token,
			visited: BTreeSet::new(),
			builders: Vec::new(),
		}
	}

	/// The Rust `Schema` expression for a type used as a struct/choice member.
	/// Named `SEQUENCE`/`CHOICE` types resolve to a builder call; primitives and
	/// keywords inline; `SEQUENCE OF X` maps through.
	fn member_expr(&mut self, type_name: &str) -> String {
		let type_name = type_name.trim();

		if let Some(inner) = type_name.strip_prefix("SEQUENCE OF ") {
			let element = self.member_expr(inner);
			return format!("Schema::SequenceOf(Box::new({element}))");
		}

		match type_name {
			"UTF8String" => return "Schema::Utf8".to_string(),
			"GeneralizedTime" => return "Schema::Date".to_string(),
			"OBJECT IDENTIFIER" => return "Schema::Oid".to_string(),
			"OCTET STRING" => return "Schema::OctetString".to_string(),
			_ => {}
		}

		let is_named_struct_or_choice = self.choices.contains_key(type_name)
			|| self.sequences.contains_key(type_name)
			|| self.ext_structs.contains_key(type_name);
		if is_named_struct_or_choice {
			let builder = self.ensure_builder(type_name);
			return format!("{builder}()");
		}

		if self.enumerations.contains_key(type_name) {
			return "Schema::Utf8".to_string();
		}
		if let Some(primitive) = self.primitives.get(type_name).cloned() {
			let aliased = alias_type(&primitive);
			return self.member_expr(aliased);
		}
		if let Some(def) = self.sensitive_by_token.get(type_name).cloned() {
			let is_sequence = def["type"].as_str() == Some("SEQUENCE");
			if is_sequence {
				let builder = self.ensure_builder(type_name);
				return format!("{builder}()");
			}

			let aliased = alias_type(&def);
			return self.member_expr(aliased);
		}

		panic!("unknown iso20022 type: {type_name}");
	}

	/// Register (once) a builder function for a named struct/choice, returning
	/// its function name.
	fn ensure_builder(&mut self, type_name: &str) -> String {
		let snake = camel_to_snake_case(type_name);
		let fn_name = format!("{snake}_schema");
		if self.visited.insert(fn_name.clone()) {
			let definition = self.define_body(type_name);
			self.builders.push((fn_name.clone(), definition));
		}

		fn_name
	}

	/// The `Schema` literal for a named struct or choice type.
	fn define_body(&mut self, type_name: &str) -> String {
		if let Some(choice) = self.choices.get(type_name).cloned() {
			return self.choice_body(&choice);
		}

		let def = self.struct_def(type_name);
		self.struct_body(&def)
	}

	/// The `Schema::Choice` literal for a CHOICE type; each alternative carries
	/// its own `[index] EXPLICIT` context tag.
	fn choice_body(&mut self, choice: &Value) -> String {
		let alternatives = choice["choices"].as_object().cloned().unwrap_or_default();
		let mut parts = Vec::new();
		for (index, alternative) in alternatives.values().enumerate() {
			let aliased = alias_type(alternative);
			let inner = self.member_expr(aliased);
			parts.push(format!("Schema::Context({index}, Box::new({inner}))"));
		}

		format!("Schema::Choice(vec![{}])", parts.join(", "))
	}

	/// The `Schema::Struct` literal for a SEQUENCE type. When the sequence has
	/// any optional member every non-CHOICE member is positionally
	/// `[index] EXPLICIT`; a CHOICE member is left bare so its alternative tag
	/// survives.
	fn struct_body(&mut self, def: &Value) -> String {
		let order = def["field_order"].as_array().cloned().unwrap_or_default();
		let fields = def["fields"].as_object().cloned().unwrap_or_default();
		let has_optional = order
			.iter()
			.filter_map(|name| name.as_str())
			.any(|name| is_optional_field(&fields[name]));

		let mut members = Vec::new();
		for (index, name) in order.iter().filter_map(|name| name.as_str()).enumerate() {
			let field = &fields[name];
			let field_type = alias_type(field);
			let is_choice = self.is_choice_type(field_type);
			let inner = self.member_expr(field_type);

			let positioned = if is_choice {
				inner
			} else if has_optional {
				format!("Schema::Context({index}, Box::new({inner}))")
			} else {
				inner
			};

			let member = if is_optional_field(field) {
				format!("Schema::Optional(Box::new({positioned}))")
			} else {
				positioned
			};

			members.push(format!("Field::new(\"{name}\", {member})"));
		}

		format!("Schema::Struct(vec![{}])", members.join(", "))
	}

	/// Whether a type ultimately resolves to a CHOICE.
	fn is_choice_type(&self, type_name: &str) -> bool {
		let type_name = type_name.trim();
		if self.choices.contains_key(type_name) {
			return true;
		}
		if let Some(primitive) = self.primitives.get(type_name) {
			let aliased = alias_type(primitive);
			return self.is_choice_type(aliased);
		}
		if let Some(def) = self.sensitive_by_token.get(type_name) {
			let is_sequence = def["type"].as_str() == Some("SEQUENCE");
			if !is_sequence {
				let aliased = alias_type(def);
				return self.is_choice_type(aliased);
			}
		}

		false
	}

	/// The SEQUENCE definition for a named struct type (an iso20022 sequence, a
	/// structural extension, or a structured sensitive attribute).
	fn struct_def(&self, type_name: &str) -> Value {
		self.sequences
			.get(type_name)
			.or_else(|| self.ext_structs.get(type_name))
			.or_else(|| self.sensitive_by_token.get(type_name))
			.cloned()
			.unwrap_or_else(|| panic!("unknown iso20022 struct type: {type_name}"))
	}
}

/// The `type` a definition aliases (a field, primitive, choice alternative, or
/// sensitive attribute).
fn alias_type(def: &Value) -> &str {
	def["type"].as_str().unwrap_or_default()
}

/// Whether a struct field is declared optional.
fn is_optional_field(field: &Value) -> bool {
	field["optional"].as_bool().unwrap_or(false)
}

/// Ensure `src/generated.rs` declares a `serde`-gated generated submodule once.
fn ensure_generated_module_serde(module: &str) {
	let generated_rs_path = Path::new("src/generated.rs");
	let current_content = fs::read_to_string(generated_rs_path).expect("Failed to read generated.rs");

	let mod_decl = format!("pub mod {module};");
	if current_content.contains(&mod_decl) {
		return;
	}

	let mut updated = current_content.trim_end().to_string();
	updated
		.push_str(&format!("\n#[cfg(feature = \"serde\")]\n#[path = \"generated/{module}.rs\"]\npub mod {module};\n"));

	fs::write(generated_rs_path, updated).expect("Failed to update generated.rs");
}

fn load_oids_json() -> Value {
	let oids = keetanetwork_asn1::utils::get_oid_json();
	serde_json::from_str(&oids).expect("Failed to parse OIDs JSON")
}

fn format_oid_comment(oid_array: &[Value]) -> String {
	let numbers: Vec<String> = oid_array
		.iter()
		.filter_map(|v| v.as_u64())
		.map(|n| n.to_string())
		.collect();
	numbers.join(".")
}

fn generate_attribute_from_impl(oids: &Value) {
	let dest_path = Path::new("src/generated").join("from_impls.rs");
	let mut generated_code = String::new();
	generated_code.push_str("use crate::asn1::{oids, error::AnchorAsn1Error};\n");
	generated_code.push_str("use crate::generated::{Attribute, AttributeValue};\n");
	generated_code.push_str("use keetanetwork_asn1::generated::iso20022::*;\n");
	generated_code.push_str("use rasn::types::OctetString;\n\n");

	// Generate TryFrom implementations for structured types in sensitive attributes
	if let Some(sensitive_attrs) = oids["sensitive_attributes"].as_object() {
		for (name, info) in sensitive_attrs {
			if let (Some(token), Some(_oid_array), Some(attr_type)) =
				(info["token"].as_str(), info["oid"].as_array(), info["type"].as_str())
			{
				let const_name = format!("oids::keeta::{}", camel_to_snake_upper(name));

				match attr_type {
					"SEQUENCE" | "CHOICE" => {
						let type_name = if let Some(stripped) = token.strip_suffix("Attribute") {
							stripped.to_string()
						} else {
							token.to_string()
						};

						generated_code.push_str(&format!(
							r#"impl TryFrom<{type_name}> for Attribute {{
	type Error = AnchorAsn1Error;

	fn try_from(value: {type_name}) -> Result<Self, Self::Error> {{
		let name = {const_name};
		let encoded = rasn::der::encode(&value)?;
		let value = AttributeValue::sensitiveValue(OctetString::from_slice(&encoded));
		Ok(Attribute {{ name, value }})
	}}
}}

"#
						));
					}
					_ => {} // Skip primitive types as they're handled by builder extensions
				}
			}
		}
	}

	// Ensure the src/generated directory exists
	if let Some(parent) = dest_path.parent() {
		fs::create_dir_all(parent).expect("Failed to create src/generated directory");
	}

	fs::write(&dest_path, generated_code).expect("Failed to write from_impls.rs");
}

fn generate_builder_trait_extension(oids: &Value) {
	let dest_path = Path::new("src/generated").join("builder_ext.rs");
	let mut generated_code = String::new();

	// Add module header and imports
	generated_code.push_str(
		r#"//! Generated trait extension for AttributeBuilderLike with typed methods
//!
//! This module provides a trait extension that adds `for_*` methods for all
//! available KYC attributes, making the builder API more ergonomic and type-safe.

use crate::kyc_schema::builder::AttributeBuilderLike;
use crate::generated::Attribute;
use crate::asn1::oids;

/// Extension trait for [`AttributeBuilderLike`] providing typed methods for KYC attributes.
///
/// This trait extends the basic [`AttributeBuilderLike`] functionality with convenience
/// methods for creating attributes with predefined OIDs. Each method is infallible
/// and will panic if the attribute cannot be created.
pub trait AttributeBuilderExtensions: AttributeBuilderLike + Sized {
"#,
	);

	// Collect all attributes from different sources
	let mut all_attributes = Vec::new();

	// Add plain attributes
	if let Some(plain_attrs) = oids["plain_attributes"].as_object() {
		for (name, info) in plain_attrs {
			if let Some(oid_array) = info["oid"].as_array() {
				let oid_comment = format_oid_comment(oid_array);
				let type_str = info["type"].as_str().unwrap_or("UTF8String");
				all_attributes.push((name.clone(), oid_comment, false, "plain", type_str.to_string()));
			}
		}
	}

	// Add sensitive attributes (all types)
	if let Some(sensitive_attrs) = oids["sensitive_attributes"].as_object() {
		for (name, info) in sensitive_attrs {
			if let Some(oid_array) = info["oid"].as_array() {
				let oid_comment = format_oid_comment(oid_array);
				let type_str = info["type"].as_str().unwrap_or("Unknown");
				all_attributes.push((name.clone(), oid_comment, true, "sensitive", type_str.to_string()));
			}
		}
	}

	// Sort attributes alphabetically for consistent output
	all_attributes.sort_by(|a, b| a.0.cmp(&b.0));

	// Generate methods for each attribute
	for (attr_name, _oid_comment, is_sensitive, source, attr_type) in &all_attributes {
		// Skip complex types since we now have TryFrom implementations for them
		if matches!(attr_type.as_str(), "SEQUENCE" | "CHOICE") {
			continue;
		}

		let method_name = format!("for_{}", camel_to_snake_case(attr_name));
		let sensitivity = if *is_sensitive {
			"sensitive"
		} else {
			"plain"
		};
		let const_name = if *source == "plain" {
			match attr_name.as_str() {
				"postalCode" => "oids::ADDRESS_POSTAL_CODE".to_string(),
				_ => format!("oids::ADDRESS_{}", attr_name.to_uppercase()),
			}
		} else {
			format!("oids::keeta::{}", camel_to_snake_upper(attr_name))
		};

		// Generate method signatures for simple types only
		generated_code.push_str(&format!(
			r#"	/// Create a {attr_name} attribute ({sensitivity})
	///
	/// Creates a {sensitivity} attribute for {attr_name} with the predefined OID.
	///
	/// # Arguments
	///
	/// - `value` - The attribute value as bytes
	fn {method_name}<V: AsRef<[u8]>>(value: V) -> Attribute {{
		Self::default()
			.with_oid({const_name})
			.with_value(value)
			.as_{sensitivity}()
			.build()
			.expect("Failed to build {attr_name} attribute")
	}}

"#
		));
	}

	// Close the trait
	generated_code.push_str("}\n\n");

	// Implement the trait for AttributeBuilder
	generated_code.push_str(
		r#"// Implement the extension trait for any type that implements AttributeBuilderLike
impl<T: AttributeBuilderLike> AttributeBuilderExtensions for T {}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::kyc_schema::builder::AttributeBuilder;

	struct AttributeTestData {
		method_name: &'static str,
		test_value: &'static [u8],
		expected_sensitivity: bool,
	}

	const ATTRIBUTE_TEST_DATA: &[AttributeTestData] = &[
"#,
	);

	// Generate test data for each attribute
	let mut test_data_entries = Vec::new();
	for (attr_name, _oid_comment, is_sensitive, _source, attr_type) in &all_attributes {
		let method_name = format!("for_{}", camel_to_snake_case(attr_name));

		// Only generate tests for simple types that can be tested with byte values
		if matches!(attr_type.as_str(), "UTF8String" | "GeneralizedTime") {
			test_data_entries.push(format!(
				r#"		AttributeTestData {{
			method_name: "{method_name}",
			test_value: b"test_{attr_name}_value",
			expected_sensitivity: {is_sensitive},
		}}"#
			));
		}
	}

	generated_code.push_str(&test_data_entries.join(",\n"));
	generated_code.push_str(
		r#"
	];

	#[test]
	fn test_all_attribute_builder_extensions() {
		for test_data in ATTRIBUTE_TEST_DATA {
			// Test that each method exists and works correctly
			let result = match test_data.method_name {
"#,
	);

	// Generate match arms for each testable method (simple types only)
	for (attr_name, _oid_comment, _is_sensitive, _source, attr_type) in &all_attributes {
		if matches!(attr_type.as_str(), "UTF8String" | "GeneralizedTime") {
			let method_name = format!("for_{}", camel_to_snake_case(attr_name));
			generated_code.push_str(&format!(
				r#"				"{method_name}" => AttributeBuilder::{method_name}(test_data.test_value),
"#
			));
		}
	}

	generated_code.push_str(
		r#"				_ => panic!("Unknown method: {}", test_data.method_name),
			};

			// Verify the attribute was created correctly
			assert_eq!(result.is_sensitive(), test_data.expected_sensitivity, 
				"Method {} should create {} attribute", 
				test_data.method_name, 
				if test_data.expected_sensitivity { "sensitive" } else { "plain" }
			);

			// Verify the value was set correctly
			let expected_value = test_data.test_value;
			let actual_value = result.as_ref();
			assert_eq!(actual_value, expected_value,
				"Method {} should set value correctly", test_data.method_name
			);
		}
	}
"#,
	);

	// Generate the test method count
	let testable_count = all_attributes
		.iter()
		.filter(|(_, _, _, _, attr_type)| matches!(attr_type.as_str(), "UTF8String" | "GeneralizedTime"))
		.count();
	let test_count_section = format!(
		r#"
	#[test]
	fn test_method_count() {{
		// Ensure we have the expected number of testable methods (simple types only)
		assert_eq!(ATTRIBUTE_TEST_DATA.len(), {testable_count}, 
			"Expected {testable_count} testable attribute methods"); 
	}}
}}
"#
	);
	generated_code.push_str(&test_count_section);

	// Ensure the src/generated directory exists
	if let Some(parent) = dest_path.parent() {
		fs::create_dir_all(parent).expect("Failed to create src/generated directory");
	}

	fs::write(&dest_path, generated_code).expect("Failed to write builder_ext.rs");

	// Generate builder trait extension and update generated.rs
	update_generated_rs_with_builder_trait();
}

fn update_generated_rs_with_builder_trait() {
	let generated_rs_path = Path::new("src/generated.rs");
	let current_content = fs::read_to_string(generated_rs_path).expect("Failed to read generated.rs");

	// Check if both modules are already included
	if current_content.contains("mod builder_ext;") && current_content.contains("mod from_impls;") {
		return; // Already updated
	}

	// Find the insertion point (after all module declarations but before re-exports)
	let lines: Vec<&str> = current_content.lines().collect();
	let mut updated_lines = Vec::new();
	let mut inserted = false;

	for line in lines {
		// Insert before the first re-export line (which starts with "// Re-export" or "pub use")
		if (line.starts_with("// Re-export") || line.starts_with("pub use")) && !inserted {
			if !current_content.contains("mod from_impls;") {
				updated_lines.push("#[path = \"generated/from_impls.rs\"]".to_string());
				updated_lines.push("mod from_impls;".to_string());
			}
			if !current_content.contains("mod builder_ext;") {
				updated_lines.push("#[path = \"generated/builder_ext.rs\"]".to_string());
				updated_lines.push("pub mod builder_ext;".to_string());
			}
			updated_lines.push("".to_string()); // Add empty line before re-exports
			inserted = true;
		}

		updated_lines.push(line.to_string());
	}

	// If we didn't find re-exports, append at the end
	if !inserted {
		updated_lines.push("".to_string());
		if !current_content.contains("mod from_impls;") {
			updated_lines.push("#[path = \"generated/from_impls.rs\"]".to_string());
			updated_lines.push("mod from_impls;".to_string());
		}
		if !current_content.contains("mod builder_ext;") {
			updated_lines.push("#[path = \"generated/builder_ext.rs\"]".to_string());
			updated_lines.push("pub mod builder_ext;".to_string());
		}
	}

	// Write the updated content back
	let updated_content = updated_lines.join("\n");
	fs::write(generated_rs_path, updated_content).expect("Failed to update generated.rs");
}

fn camel_to_snake_case(s: &str) -> String {
	let mut result = String::new();
	let chars = s.chars().peekable();
	for c in chars {
		if c.is_uppercase() && !result.is_empty() {
			result.push('_');
		}
		result.push(c.to_lowercase().next().unwrap());
	}
	result
}

fn camel_to_snake_upper(s: &str) -> String {
	let mut result = String::new();
	let chars = s.chars().peekable();
	for c in chars {
		if c.is_uppercase() && !result.is_empty() {
			result.push('_');
		}
		result.push(c.to_uppercase().next().unwrap());
	}

	result
}
