//! Generated ASN.1 code
//!
//! This module contains all the generated ASN.1 structures and re-exports them
//! for use throughout the library.
//!
//! This file is automatically generated by build.rs - do not edit manually.

#[path = "generated/k_y_c_attributes.rs"]
mod k_y_c_attributes;
#[path = "generated/sensitive_attributes.rs"]
mod sensitive_attributes;

// Re-export all types from the generated modules
pub use k_y_c_attributes::{Attribute, AttributeValue, KYCAttributes};
pub use sensitive_attributes::{SensitiveAttribute, SensitiveAttributeCipher, SensitiveAttributeHashedValue};
