//! Generated ASN.1 code
//!
//! This module contains all the generated ASN.1 structures and re-exports them
//! for use throughout the library.
//!
//! This file is automatically generated by build.rs - do not edit manually.

#[path = "generated/iso20022.rs"]
pub mod iso20022;
#[path = "generated/k_y_c_attributes.rs"]
mod k_y_c_attributes;
#[path = "generated/sensitive_attributes.rs"]
mod sensitive_attributes;

#[path = "generated/from_impls.rs"]
mod from_impls;

#[path = "generated/builder_ext.rs"]
pub mod builder_ext;

// Re-export all types from the generated modules
pub use iso20022::{
	Address, AddressLines, AddressType, AnonymousAddressLines, BirthDate, BuildingNumber, ContactDetails, Country,
	CountrySubDivision, DateAndPlaceOfBirth, Department, EmailAddress, EmailAddressPurpose, EntityType, FullName,
	GenericOrganizationIdentification, GenericPersonIdentification, Id, Issuer, JobResponsibility, JobTitle,
	NamePrefixCode, OrganizationIdentification, OrganizationIdentificationSchemeNameChoice, OtherContact,
	PersonIdentification, PersonIdentificationSchemeNameChoice, PhoneNumber, PostalCode, PreferredContactMethodCode,
	StreetName, SubDepartment, TownName,
};
pub use k_y_c_attributes::{Attribute, AttributeValue, KYCAttributes};
pub use sensitive_attributes::{SensitiveAttribute, SensitiveAttributeCipher, SensitiveAttributeHashedValue};
